version: '3'

services:
    redis:
        image: redis
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
        env_file:
            - .env
        volumes:
            - cache:/data
    db:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - data:/var/lib/postgresql/data
            - ./migrations/initdb.sql:/docker-entrypoint-initdb.d/intidb.sql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 10
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
            redis:
volumes:
    data:
    cache:
